### ISSUE TITLE
2do_future_projection.rが実行できない

### ISSUE THREAD

**Issue by aynigisu** [ichimomo/frasyr_tool#11]
<img width="401" alt="スクリーンショット 2019-10-25 16 13 43" src="https://user-images.githubusercontent.com/56994304/67551217-57d5a700-f743-11e9-8b3f-73d61c7df672.png">

「eval(ei, envir) でエラー:  オブジェクト 'maa_in_future' がありません」
というエラーが出て、実行が途中で止まってしまうようです。

**Comment by ichimomo** [comment]
修正されたと思います
