### ISSUE TITLE
out.vpa関数で出力した CSVファイルで 0do_all.rが実行できない

### ISSUE THREAD

**Issue by sayokoisu** [ichimomo/frasyr_tool#14]
0do_all.rを実行しようとすると下のようにエラーがでて次に進めなくなりました。

> source("1do_MSYest.r", encoding="UTF-8")
Pope is TRUE... OK?
## --------------------------------------------------------
# A tibble: 1 x 7
       a      b    sd   rho  AICc method type 
   <dbl>  <dbl> <dbl> <dbl> <dbl> <chr>  <chr>
1 0.0253 54485. 0.320 0.446  34.6 L2     HS   
## --------------------------------------------------------
Error in (function (res0, currentF = NULL, multi = 1, nyear = 10, Pope = res0$input$Pope,  : 
  unused arguments (futureF = NULL, waa.catch.year = NULL, MSE.options = NULL)
> # 科学者会議で計算：推定した管理基準値で将来予測
> source("2do_future_projection.r", encoding="UTF-8")
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection

**Comment by ichimomo** [comment]
frasyrが最新のものになっているか確かめてください

2019年10月28日(月) 17:42 sayokoisu <notifications@github.com>:

**Comment by ichimomo** [comment]
もし解決された場合はご報告いただけたらうれしいです．

**Comment by sayokoisu** [comment]
先ほどはありがとうございました。VPAを回す際に使っていた関数が古かったことを教えていただきました。
