### ISSUE TITLE
2do_future_projection.rのKobe Chartでの説明がおかしい

### ISSUE THREAD

**Issue by fshin3** [ichimomo/frasyr_tool#28]
KOBE Plotの図で、「目標管理基準値」と「禁漁水準」のインデックスが反対になっている

**Comment by fshin3** [comment]
2do_future_projection.rの３３３行目
label_name_kobe <- c("禁漁水準","限界管理基準値","目標管理基準値")
の表記を
label_name_kobe <- c("目標管理基準値","限界管理基準値","禁漁水準")
に、８２７行目も同様に修正。

**Comment by ichimomo** [comment]
この修正で良くなったと思います。
label_name_kobe <- c("目標管理基準値","限界管理基準値","禁漁水準")
と設定してください。
