### ISSUE TITLE
正規性の検定

### ISSUE THREAD

**Issue by ShotaNishijima** [ichimomo/frasyr_tool#33]
再生産関係の診断で2つの正規性の検定の結果が違ってどう解釈すればいいのか？という質問がくるので、わかりやすく。小サンプルのSW検定を優先すればいいと思うので、そちらだけど初期設定にして、KS検定をオプションにするか

**Comment by ShotaNishijima** [comment]
Shapiro-Wilkのみを初期設定にして、Kolmogorov-Smirnovはオプションで選べるようにしました。いまdevを変更すると混乱しそうなので、とりあえずnishijimaブランチを作りました。

https://github.com/ichimomo/frasyr_tool/blob/6eb4eaff8dbc740577d26e14735575cc4469062f/example/1do_MSYest.r#L44-L46

**Comment by ichimomo** [comment]
ありがとうございます．確認しました．

今後，masterの変更頻度を減らし，devにはどんどん新しいバージョンを入れていこうと思うので，こちらの変更についてもdevにマージしてしまってください．

どうぞよろしくお願い致します。

**Comment by ShotaNishijima** [comment]
#34 をmergeしたので完了
